apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: authapp
  template:
    metadata:
      labels:
        app: authapp
    spec:
      containers:
        - name: auth
          image: indrajithvgp/auth-app:latest